package com.pekings.pos.util;

/**
 * Projection interface for representing sales data of menu items.
 * Used to retrieve aggregated statistics such as total orders and revenue for individual menu items.
 */
public interface SaleItem {

    /**
     * Gets the ID of the menu item.
     *
     * @return The ID of the menu item as an integer.
     */
    int getMenuItemID();

    /**
     * Gets the name of the menu item.
     *
     * @return The name of the menu item as a {@link String}.
     */
    String getName();

    /**
     * Gets the total number of orders placed for the menu item.
     *
     * @return The total orders as an integer.
     */
    int getTotalOrders();

    /**
     * Gets the total revenue generated by the menu item.
     *
     * @return The total revenue as a double.
     */
    double getTotalRevenue();
}
